# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4d7492274297b9c49efa3d477076925aec8d1da52782e48c3e1ac2dbf9e8c3da1869ab8f54b2732440496ad53cab824015d4e4c1e23c51744132ed6c92f3fa7

test:
  secret_key_base: 972770591b5475254efeed3d365b8cda9ac068123682bd16ace4e417a2405007af4b066900452c988251803589d719f15670acc589e9970855557f8e5d455e9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
